apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: crate-db
  name: crate-db
spec:
  type: LoadBalancer
  externalIPs:
  - EXTERNAL_IP
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  - name: "4300"
    port: 4300
    targetPort: 4300
  selector:
    io.kompose.service: crate-db
status:
  loadBalancer: {}
