apiVersion: apps/v1
kind: Deployment
metadata:
   name: client
   labels:
      app: client
spec:
   replicas: 10
   selector:
      matchLabels:
        app: client
   template:
     metadata:
       labels:
         app: client
     spec:
       containers:
       - name: client
         image: gitlab.ilabt.imec.be:4567/brvdvyve/ngsi-vs-fragments-client
         env:
         - name: METHOD # latest or aggregation method (average, median)
           value: "latest"
         - name: API
           value: "fragments" # fragments or ngsi
         - name: PORT
           value: "1234" # 5000: fragments API, 1234: NGINX proxy to fragments, 4300 QuantumLeap
         - name: AGGRPERIOD # year, month, day, hour, minute, second
           value: "minute"
         # - name: FROMDATE
         #   value: "2019-01-05T15:44:34"
         # - name: TODATE
         #   value: "2019-03-05T15:44:34"
         # resources:
         #  requests:
         #    memory: "35Mi"
         #    cpu: "10m"
         #  limits:
         #    memory: "55Mi"
         #    cpu: "60m"
