apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orion
  template:
    metadata:
      labels:
        io.kompose.service: orion
    spec:
      containers:
      - name: orion
        image: fiware/orion:2.2.0
        ports:
        - containerPort: 1026
        args: ["-dbhost", "mongo-db"]