apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "." #host location