apiVersion: apps/v1
kind: Deployment
metadata:
   name: client
   labels:
      app: client
spec:
   replicas: 10
   selector:
      matchLabels:
        app: client
   template:
     metadata:
       labels:
         app: client
     spec:
       containers:
       - name: client
         image: gitlab.ilabt.imec.be:4567/brvdvyve/ngsi-client-benchmark
         # resources:
         #  requests:
         #    memory: "35Mi"
         #    cpu: "10m"
         #  limits:
         #    memory: "55Mi"
         #    cpu: "60m"
